# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

addons:
  apt:
    packages:
      - xclip

before_script:
  - "export DISPLAY=':0.0'"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
