# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - xsel

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

env:
  global:
    - DISPLAY=:99.0
    - _R_CHECK_FORCE_SUGGESTS_=false

matrix:
  include:
    - r: devel
    - r: release
      after_success:
      - Rscript -e 'covr::codecov()'
      - find . -name testthat.Rout | xargs cat
      after_failure:
      - find . -name testthat.Rout | xargs cat
      before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")' -e 'remotes::install_github("tidyverse/tidytemplate")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
        skip_cleanup: true
    - r: 3.5
    - r: 3.4
    - r: 3.3
    - r: 3.2
