# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
sudo: false
cache: packages

addons:
  apt:
    packages:
      - xclip

before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 3

r:
  - 3.1
  - 3.2
  - oldrel
  - release
  - devel
env:
  - DISPLAY=:99.0
matrix:
  allow_failures:
    - r: 3.1
  include:
    - r: release
      env: DISPLAY=""

after_success:
  - Rscript -e 'covr::codecov()'
